name: ubuntu

on:
    push:
        branches:
            - '**'
            - '!**windows**'
            - '!**macos**'
        tags-ignore:
            - 'release-*'
        paths-ignore:
            - '.appveyor.yml'
            - '.github/workflows/macos.yml'
            - '.github/workflows/windows.yml'
            - '.gitignore'
            - '.releaserc'
            - 'Changes'
            - 'LICENSE'
            - 'README.pod'
        pull_request:

jobs:
    perl:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            os:
                - ubuntu-18.04
                - ubuntu-20.04
            perl-version:
                - '5.10'
                - 'latest'
        container:
            image: perl:${{ matrix.perl-version }}
        steps:
            - uses: actions/checkout@v2
            - name: Platform check
              run: uname -a
            - name: Perl version check
              run: perl -V
            - name: Install cpanm and multiple modules
              run: |
                curl -L https://cpanmin.us | perl - App::cpanminus
                cpanm --notest IO::Socket::SSL App::Cpan ExtUtils::MakeMaker LWP LWP::Protocol::https App::Cpan
                cpan -M https://www.cpan.org -T ExtUtils::MakeMaker
            - name: Install dependencies
              run: |
                cpan -M https://www.cpan.org -T .
            - name: Run tests
              run: |
                perl Makefile.PL
                make test
            - name: Run tests in parallel
              run: |
                perl Makefile.PL
                HARNESS_OPTIONS=j10 make test
            - name: Run distribution tests
              run: |
                perl Makefile.PL
                make disttest
            - name: Run coverage tests
              if: env.PERL_VERSION != 'v5.8'
              run: |
                cpan -M https://www.cpan.org -T Devel::Cover Devel::Cover::Report::Coveralls
                cover -test -report coveralls
